baseurl: /blog

collections:
  authors:
    output: true
    permalink: /authors/:path/

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: authors
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
